# Assignment 1

## Task 1

In [115]:
transactions = [
    {"id": 1, "product": "Laptop", "price": 1200, "quantity": 2, "region": "EU"},
    {"id": 2, "product": "Phone", "price": 800, "quantity": -1, "region": "US"},
    {"id": 3, "product": "Tablet", "price": 0, "quantity": 5, "region": "EU"},
    {"id": 4, "product": "Monitor", "price": 350, "quantity": 3, "region": "US"},
    {"id": 5, "product": "Laptop", "price": 1200, "quantity": 1, "region": "EU"},
    {"id": 6, "product": "Keyboard", "price": 75, "quantity": 10, "region": "APAC"},
]

In [116]:
# Filter out invalid transactions
valid_transactions = []

for t in transactions:
    if t["price"] > 0 and t["quantity"] >= 0:
        valid_transactions.append(t)

valid_transactions

[{'id': 1, 'product': 'Laptop', 'price': 1200, 'quantity': 2, 'region': 'EU'},
 {'id': 4, 'product': 'Monitor', 'price': 350, 'quantity': 3, 'region': 'US'},
 {'id': 5, 'product': 'Laptop', 'price': 1200, 'quantity': 1, 'region': 'EU'},
 {'id': 6,
  'product': 'Keyboard',
  'price': 75,
  'quantity': 10,
  'region': 'APAC'}]

In [117]:
# Add total revenue for each valid transaction
for t in valid_transactions:
    t["total"] = t["price"] * t["quantity"]

valid_transactions

[{'id': 1,
  'product': 'Laptop',
  'price': 1200,
  'quantity': 2,
  'region': 'EU',
  'total': 2400},
 {'id': 4,
  'product': 'Monitor',
  'price': 350,
  'quantity': 3,
  'region': 'US',
  'total': 1050},
 {'id': 5,
  'product': 'Laptop',
  'price': 1200,
  'quantity': 1,
  'region': 'EU',
  'total': 1200},
 {'id': 6,
  'product': 'Keyboard',
  'price': 75,
  'quantity': 10,
  'region': 'APAC',
  'total': 750}]

In [118]:
revenue_per_region = {}

for t in valid_transactions:
    region = t["region"]
    
    if region not in revenue_per_region:
        revenue_per_region[region] = 0
    
    revenue_per_region[region] += t["total"]

revenue_per_region

{'EU': 3600, 'US': 1050, 'APAC': 750}

In [119]:
# Find the region with highest revenue
best_region = max(revenue_per_region, key=revenue_per_region.get)
best_value = revenue_per_region[best_region]

print(f"Best region: {best_region} with revenue {best_value}")

Best region: EU with revenue 3600


## Task 2

In [120]:
sales = [1200, 980, 1540, 870, 2010, 1650, 1300, 1100, 950, 1780, 2200, 1430, 1600, 1900]

In [121]:
def summarise_sales(sales):
    # Calculate total and average sales
    total = sum(sales)
    average = round(total / len(sales), 2)

    # Find best and worst day ( starting from day 1 )
    best_day = sales.index(max(sales)) + 1
    worst_day = sales.index(min(sales)) + 1
    
    # Count how many days were above average
    above_average_count = 0
    for value in sales:
        if value > average:
            above_average_count += 1

    return {
        "total": total,
        "average": average,
        "best_day": best_day,
        "worst_day": worst_day,
        "above_average_count": above_average_count
    }

In [122]:
result = summarise_sales(sales)
print(result)

{'total': 20510, 'average': 1465.0, 'best_day': 11, 'worst_day': 4, 'above_average_count': 7}


## Task 3

In [123]:
students = [
    {"name": "Anna", "grade": 85, "attendance": 0.92},
    {"name": "Erik", "grade": 58, "attendance": 0.75},
    {"name": "Mia", "grade": 91, "attendance": 0.98},
    {"name": "Leo", "grade": 44, "attendance": 0.60},
    {"name": "Sara", "grade": 72, "attendance": 0.88},
    {"name": "Tom", "grade": 67, "attendance": 0.70},
    {"name": "Nina", "grade": 95, "attendance": 0.99},
    {"name": "Olli", "grade": 50, "attendance": 0.65},
]

### Task 3a

In [124]:
# Collect names of students with passing grade
passing = []

for s in students:
    if s["grade"] >= 50:
        passing.append(s["name"])

print(passing)

['Anna', 'Erik', 'Mia', 'Sara', 'Tom', 'Nina', 'Olli']


### Task 3b

In [125]:
for s in students:
    name = s["name"]
    grade = s["grade"]

    if grade >= 80:
        print(f"{name}: Excellent")
    elif grade >= 50:
        print(f"{name}: Pass")
    else:
        print(f"{name}: Fail")

Anna: Excellent
Erik: Pass
Mia: Excellent
Leo: Fail
Sara: Pass
Tom: Pass
Nina: Excellent
Olli: Pass


### Task 3c

In [126]:
# Count student with attendance below 80%
count = 0

for s in students:
    if s["attendance"] < 0.80:
        count += 1

print(count)

4


### Task 3d

In [127]:
# Find the student with the highest grade without using max ()
best_student = students[0]

for s in students:
    if s["grade"] > best_student["grade"]:
        best_student = s

print(best_student["name"], best_student["grade"])

Nina 95


### Task 3e

In [128]:
# Find the student with the highest grade using max ()
best = max(students, key=lambda s: s["grade"])

print(best["name"], best["grade"])

Nina 95


## Task 4

In [129]:
class Portfolio:
    def __init__(self, owner):
        self.owner = owner
        self.holdings = {} # Store asset by ticker symbol

    def add_asset(self, ticker, shares, price_per_share):
        # Add a new asset or update an existing one
        self.holdings[ticker] = {
            "shares": shares,
            "price_per_share": price_per_share
        }

    def total_value(self):
        # Calculate the total market value of the portfolio
        total = 0
        for asset in self.holdings.values():
            total += asset["shares"] * asset["price_per_share"]
        return total

    def most_valuable(self):
        # Find the asset with the highest total value
        best = None
        max_value = 0

        for ticker, asset in self.holdings.items():
            value = asset["shares"] * asset["price_per_share"]
            if value > max_value:
                max_value = value
                best = ticker

        return best

    def __str__(self):
        return f"Owner: {self.owner}, Assets: {len(self.holdings)}, Total Value: {self.total_value()}"

In [130]:
p = Portfolio("Alex")

p.add_asset("AAPL", 10, 150)
p.add_asset("TSLA", 5, 700)
p.add_asset("GOOG", 2, 2000)

print(p)
print("Total value:", p.total_value())
print("Most valuable:", p.most_valuable())

Owner: Alex, Assets: 3, Total Value: 9000
Total value: 9000
Most valuable: GOOG


## Task 5

In [131]:
orders = [
    ("2025-01-15", "Laptop"), ("2025-01-22", "Phone"),
    ("2025-02-03", "Laptop"), ("2025-02-14", "Tablet"),
    ("2025-03-01", "Phone"), ("2025-03-10", "Phone"),
    ("2025-03-22", "Laptop"), ("2025-04-05", "Monitor"),
]

In [132]:
from datetime import datetime

# Convert date stings to date objects
dates = []

for date_str, product in orders:
    date_obj = datetime.strptime(date_str, "%Y-%m-%d").date()
    dates.append(date_obj)

# Find earliest and latess order dates
earliest = min(dates)
latest = max(dates)

difference = (latest - earliest).days

print("Days between:", difference)

Days between: 80


## Task 6

In [133]:
import numpy as np

revenue = np.array([
    [210, 230, 190, 250],
    [220, 260, 200, 270],
    [250, 290, 230, 310]
])

### Task 6a

In [134]:
# Sum each row to get annual revenue
annual_totals = revenue.sum(axis=1)
print(annual_totals)

[ 880  950 1080]


### Task 6b

In [135]:
# Calculate the mean revenue for each quarter
quarter_means = revenue.mean(axis=0)
print(quarter_means)

[226.66666667 260.         206.66666667 276.66666667]


### Task 6c

In [136]:
# Apply quarterly growth adjustments to 2024 revenue
growth = np.array([1.05, 1.03, 1.08, 1.02])

adjusted_2024 = revenue[2] * growth
print(adjusted_2024)

[262.5 298.7 248.4 316.2]


### Task 6d

In [137]:
# Select all revenue values greater than 250
high_values = revenue[revenue > 250]
print(high_values)

[260 270 290 310]


## Task 7

In [138]:
import pandas as pd

data = {
    "employee": ["Anna", "Erik", "Mia", "Leo", "Sara", "Tom"],
    "department": ["Finance", "Marketing", "Finance", "IT", "Marketing", "IT"],
    "salary": [4500, 4000, 4800, 5200, 3900, 5100],
    "years_exp": [5, 3, 7, 10, 2, 8],
    "performance_score": [4.2, 3.8, 4.5, 4.0, 3.5, 4.9]
}

df = pd.DataFrame(data)
df

,employee,department,salary,years_exp,performance_score
0,Anna,Finance,4500,5,4.2
1,Erik,Marketing,4000,3,3.8
2,Mia,Finance,4800,7,4.5
3,Leo,IT,5200,10,4.0
4,Sara,Marketing,3900,2,3.5
5,Tom,IT,5100,8,4.9


### Task 7a

In [139]:
# Create a new column for salary per year of experience
df["salary_per_year_exp"] = (df["salary"] / df["years_exp"]).round()
df

,employee,department,salary,years_exp,performance_score,salary_per_year_exp
0,Anna,Finance,4500,5,4.2,900.0
1,Erik,Marketing,4000,3,3.8,1333.0
2,Mia,Finance,4800,7,4.5,686.0
3,Leo,IT,5200,10,4.0,520.0
4,Sara,Marketing,3900,2,3.5,1950.0
5,Tom,IT,5100,8,4.9,638.0


### Task 7b

In [140]:
# Sort by performance score and select the top 3 employees
top3 = df.sort_values(by="performance_score", ascending=False).head(3)
print(top3)

  employee department  salary  years_exp  performance_score  \
5      Tom         IT    5100          8                4.9   
2      Mia    Finance    4800          7                4.5   
0     Anna    Finance    4500          5                4.2   

   salary_per_year_exp  
5                638.0  
2                686.0  
0                900.0  


### Task 7c

In [141]:
# Select Finance employees with performance score above 4.0
finance_high = df.loc[
    (df["department"] == "Finance") & (df["performance_score"] > 4.0)
]

print(finance_high)

  employee department  salary  years_exp  performance_score  \
0     Anna    Finance    4500          5                4.2   
2      Mia    Finance    4800          7                4.5   

   salary_per_year_exp  
0                900.0  
2                686.0  


### Task 7d

In [142]:
# Rename years_exp to experience_years
df = df.rename(columns={"years_exp": "experience_years"})
df

,employee,department,salary,experience_years,performance_score,salary_per_year_exp
0,Anna,Finance,4500,5,4.2,900.0
1,Erik,Marketing,4000,3,3.8,1333.0
2,Mia,Finance,4800,7,4.5,686.0
3,Leo,IT,5200,10,4.0,520.0
4,Sara,Marketing,3900,2,3.5,1950.0
5,Tom,IT,5100,8,4.9,638.0


### Task 7e

In [143]:
# Select salary and performance score for the first four employees
subset = df.iloc[0:4][["salary", "performance_score"]]
print(subset)

   salary  performance_score
0    4500                4.2
1    4000                3.8
2    4800                4.5
3    5200                4.0


## Task 8

In [46]:
import numpy as np
import pandas as pd

rng = np.random.default_rng(seed=123)
days = pd.date_range(start="2025-01-06", periods=28, freq="D")
visitors = rng.integers(200, 600, size=28)
conversion_rate = rng.uniform(0.02, 0.08, size=28).round(4)
avg_order_value = rng.normal(50, 10, size=28).round(2)

### Task 8a

In [144]:
# Create a DataFrame and set date as the index
df = pd.DataFrame({
    "date": days,
    "visitors": visitors,
    "conversion_rate": conversion_rate,
    "avg_order_value": avg_order_value
})

df = df.set_index("date")

df

,visitors,conversion_rate,avg_order_value
date,,,
2025-01-06,206,0.0645,64.30
2025-01-07,472,0.0578,48.44
2025-01-08,437,0.0756,43.26
2025-01-09,221,0.0339,43.61
2025-01-10,563,0.0679,49.39
2025-01-11,288,0.0511,46.07
2025-01-12,302,0.0339,72.90
2025-01-13,273,0.0300,42.82
2025-01-14,333,0.0499,50.33


### Task 8b

In [145]:
# Calculate daily conversions and revenue
df["conversions"] = (df["visitors"] * df["conversion_rate"]).round()

df["daily_revenue"] = df["conversions"] * df["avg_order_value"]

df

,visitors,conversion_rate,avg_order_value,conversions,daily_revenue
date,,,,,
2025-01-06,206,0.0645,64.30,13.0,835.90
2025-01-07,472,0.0578,48.44,27.0,1307.88
2025-01-08,437,0.0756,43.26,33.0,1427.58
2025-01-09,221,0.0339,43.61,7.0,305.27
2025-01-10,563,0.0679,49.39,38.0,1876.82
2025-01-11,288,0.0511,46.07,15.0,691.05
2025-01-12,302,0.0339,72.90,10.0,729.00
2025-01-13,273,0.0300,42.82,8.0,342.56
2025-01-14,333,0.0499,50.33,17.0,855.61
